### ISSUE TITLE
How do you set chromecast options?

### ISSUE THREAD

**Issue by ntamblyn** [benjipott/video.js-chromecast#10]
How do you set the appId and metadata for this plugin ?

Whenever i try using player.chromecast(); i get the error message that Uncaught TypeError: player.chromecast is not a function. 

if i try and add player.chromecast.options.appId = "APP-ID"; 
i just get a random Generated ID.

Some guidance with this would be much appreciated.

**Comment by DoubleYo** [comment]
Hello, I have the same issue. Have you figure it out ? There is still not doc.

**Comment by bilalghouri** [comment]
Same issue.

**Comment by benjipott** [comment]
you can set it here https://github.com/benjipott/video.js-chromecast/blob/master/src/js/component/control-bar/chromecast-button.js#L59

```
videojs.('playerId', {
     chromecast :
         appId:'yourAppID'
     }
})
```
