### ISSUE TITLE
HLS livestream with infinity not playing from live

### ISSUE THREAD

**Issue by Jrubensson** [benjipott/video.js-chromecast#16]
We've got a livestreaming service using this plugin. A problem we encountered is that our livestream has got a length of 1 hour, and when casting one of our livestreams the Chromecast won't start the playback from live. 

Is there a way to fix this?

**Comment by onigetoc** [comment]
Update with the latest HLS plugin
https://github.com/videojs/videojs-contrib-hls/issues/988
