### ISSUE TITLE
Subtitles? .vtt

### ISSUE THREAD

**Issue by Jad3z** [benjipott/video.js-chromecast#38]
Does anyone know how to stream .vtt or .srt to chromecast with this plugin? I tried about anything but it doesn't work when casting..

**Comment by benjipott** [comment]
Hello, what is your code sample ?

**Comment by SarasotaSlim** [comment]
Having a VTT track tag breaks Chromecast plugin:

    http://weasel.firmfriends.us/OnDemandMovie/
