### ISSUE TITLE
[Fix activeTrackIds] Set the selected subtitle active before casting

### ISSUE THREAD

**Issue by payflix** [benjipott/video.js-chromecast#48]
Substitles are never casted even if selected in videojs
Adding this piece of code automatically sets the active trackId before casting

Place this code between line 251 and 252 in chromecast.js

```
var activeTrack = 0
document.querySelectorAll('.vjs-menu-content > .vjs-captions-menu-item').forEach(function(el, i) {
     if (el.classList.contains('vjs-selected')) {
          activeTrack = (i + 1)
     }
})
loadRequest.activeTrackIds = [activeTrack];
```

**Comment by benjipott** [comment]
you can make a PR, thk's

**Comment by areeb111** [comment]
@payflix 
I am still unable to cast subtitles,
Can you please let me know in which function you need to add the above code ?
Because the number of lines are changed from 1 year ago.
