### ISSUE TITLE
Subtitle menu disappears when casting

### ISSUE THREAD

**Issue by Fenny** [benjipott/video.js-chromecast#53]
VideoJS v6.6.2
VideoJs Chromecast v2.09

Subtitle menu disappears when trying to cast, when I stop casting it doesn't come back.
The vjs-hidden is toggled on the subtitle menu, but also the subtitle items seems to be removed.
Why is this happening and how to fix it?

Test on VideoJS version 4,5 & 6

![https://i.imgur.com/2YSeVMc.gif](https://i.imgur.com/2YSeVMc.gif)

**Comment by payflix** [comment]
chromecast.js calls `onMediaDiscovered` function that calls `this.player_.loadTech_('Chromecast', {` that calls `if (this.tech_) { this.unloadTech_(); }` that calls videoJS `Player.prototype.unloadTech_` function that actually removes the subtitle menu including the items. No idea how to fix this :(

**Comment by ChoOo7** [comment]
Hello

Did you manage it ?

Thanks

**Comment by prakashmuvi** [comment]
Have you find the solution of disappearing subtitle icon from control bar after cast ?

**Comment by emilsas** [comment]
Hello,

I have the same problem here. 
Did someone manage it?

Thanks
